import { Permission, PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS: Record<
  "ADMIN" | "TEACHER",
  Permission[]
> = {
  ADMIN: [
    PERMISSIONS.DASHBOARD,

    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_UPDATE,
    PERMISSIONS.STUDENTS_DELETE,

    PERMISSIONS.FEES,

    PERMISSIONS.ATTENDANCE,

    PERMISSIONS.EXAMINATION,

    PERMISSIONS.SMS,

    PERMISSIONS.SETTINGS,

    PERMISSIONS.USERS,

    PERMISSIONS.ROLES,

    PERMISSIONS.PROFILE,
  ],

  TEACHER: [
    PERMISSIONS.DASHBOARD,

    PERMISSIONS.STUDENTS_VIEW,

    PERMISSIONS.ATTENDANCE,

    PERMISSIONS.EXAMINATION,

    PERMISSIONS.PROFILE,
  ],
};