import { PERMISSIONS } from "./permissions";
import { ROLES } from "./roles";

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    // Dashboard
    PERMISSIONS.DASHBOARD_VIEW,

    // Students & Enrollments
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_UPDATE,
    PERMISSIONS.STUDENTS_DELETE,
    PERMISSIONS.STUDENT_ENROLLMENTS_VIEW,
    PERMISSIONS.STUDENT_ENROLLMENTS_CREATE,
    PERMISSIONS.STUDENT_ENROLLMENTS_UPDATE,
    PERMISSIONS.STUDENT_ENROLLMENTS_DELETE,

    // Fees
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_COLLECT,

    // Attendance
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,

    // Examination
    PERMISSIONS.EXAMINATION_VIEW,
    PERMISSIONS.EXAMINATION_CREATE,
    PERMISSIONS.EXAMINATION_UPDATE,

    // SMS
    PERMISSIONS.SMS_VIEW,
    PERMISSIONS.SMS_SEND,

    // Users & Roles
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.ROLES_VIEW,

    // Profile
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,

    // Master Settings & Academic Years
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.ACADEMIC_YEARS_VIEW,
    PERMISSIONS.ACADEMIC_YEARS_CREATE,
    PERMISSIONS.ACADEMIC_YEARS_UPDATE,
    PERMISSIONS.ACADEMIC_YEARS_DELETE,
    PERMISSIONS.ACADEMIC_YEARS_RESTORE,
    PERMISSIONS.ACADEMIC_YEARS_ACTIVATE,
    PERMISSIONS.ACADEMIC_YEARS_ARCHIVE,

    // Classes & Sections (Full Access)
    PERMISSIONS.CLASSES_VIEW,
    PERMISSIONS.CLASSES_CREATE,
    PERMISSIONS.CLASSES_UPDATE,
    PERMISSIONS.CLASSES_DELETE,
    PERMISSIONS.CLASSES_CONFIGURATION_VIEW,
    PERMISSIONS.CLASSES_CONFIGURATION_MANAGE,
    PERMISSIONS.SECTIONS_VIEW,
    PERMISSIONS.SECTIONS_CREATE,
    PERMISSIONS.SECTIONS_UPDATE,
    PERMISSIONS.SECTIONS_DELETE,
    PERMISSIONS.CLASSES_OCCUPANCY_VIEW,
    PERMISSIONS.CLASSES_AUTO_ALLOCATE,

   
  ],

  [ROLES.TEACHER]: [
    // Dashboard & Profile
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,

    // Student Roster
    PERMISSIONS.STUDENTS_VIEW,

    // Attendance & Exams
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.EXAMINATION_VIEW,

    // Academic Context & Class Roster (Read-Only)
    PERMISSIONS.ACADEMIC_YEARS_VIEW,
    PERMISSIONS.CLASSES_VIEW,
    PERMISSIONS.SECTIONS_VIEW,
    PERMISSIONS.CLASSES_OCCUPANCY_VIEW,
  ],
} as const;