import { PERMISSIONS } from "./permissions";
import { ROLES } from "./roles";

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.STUDENTS_VIEW,
  PERMISSIONS.STUDENTS_CREATE,
  PERMISSIONS.STUDENTS_UPDATE,
  PERMISSIONS.STUDENTS_DELETE,

  PERMISSIONS.FEES_VIEW,
  PERMISSIONS.FEES_COLLECT,

  PERMISSIONS.ATTENDANCE_VIEW,
  PERMISSIONS.ATTENDANCE_MARK,

  PERMISSIONS.EXAMINATION_VIEW,
  PERMISSIONS.EXAMINATION_CREATE,
  PERMISSIONS.EXAMINATION_UPDATE,

  PERMISSIONS.SMS_VIEW,
  PERMISSIONS.SMS_SEND,

  PERMISSIONS.USERS_VIEW,
  PERMISSIONS.USERS_CREATE,
  PERMISSIONS.USERS_UPDATE,
  PERMISSIONS.USERS_DELETE,

  PERMISSIONS.ROLES_VIEW,

  PERMISSIONS.PROFILE_VIEW,
  PERMISSIONS.PROFILE_UPDATE,

  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.SETTINGS_MANAGE,
],
 [ROLES.TEACHER]:[
  PERMISSIONS.DASHBOARD_VIEW,

  PERMISSIONS.STUDENTS_VIEW,

  PERMISSIONS.ATTENDANCE_VIEW,
  PERMISSIONS.ATTENDANCE_MARK,

  PERMISSIONS.EXAMINATION_VIEW,

  PERMISSIONS.PROFILE_VIEW,
  PERMISSIONS.PROFILE_UPDATE,
]
} as const;