"use client";

import { UseFormReturn } from "react-hook-form";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import {
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";

import { Input } from "@/components/ui/input";

import type { StudentFormValues } from "../schemas/student-form.schema";
import { useStudentCode } from "../hooks/use-student-code";

interface RegistrationInformationProps {
  form: UseFormReturn<StudentFormValues>;
}

export function RegistrationInformation({
  form,
}: RegistrationInformationProps) {
  const {
    data,
    isLoading,
    isError,
  } = useStudentCode();

  const registrationDate = new Date().toISOString().split("T")[0];

  return (
    <Card>
      <CardHeader>
        <CardTitle>
          Registration Information
        </CardTitle>

        <CardDescription>
          Permanent registration details of the student.
          Student Code and Registration Date are generated
          automatically by the system.
        </CardDescription>
      </CardHeader>

      <CardContent className="space-y-8">
        {/* ---------------- System Generated ---------------- */}

        <div className="space-y-4">
          <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">
            System Generated
          </h3>

          <div className="grid gap-6 md:grid-cols-2">
            {/* Student Code */}

            <div className="space-y-2">
              <FormLabel>Student Code</FormLabel>

              <Input
                value={
                  isLoading
                    ? "Loading..."
                    : data?.studentCode ?? ""
                }
                readOnly
                className="bg-muted"
              />

              <p className="text-xs text-muted-foreground">
                Automatically generated by the system.
              </p>

              {isError && (
                <p className="text-sm text-destructive">
                  Failed to generate student code.
                </p>
              )}
            </div>

            {/* Registration Date */}

            <div className="space-y-2">
              <FormLabel>Registration Date</FormLabel>

              <Input
                value={registrationDate}
                readOnly
                className="bg-muted"
              />

              <p className="text-xs text-muted-foreground">
                Automatically generated by the system.
              </p>
            </div>
          </div>
        </div>

        {/* ---------------- Government IDs ---------------- */}

        <div className="space-y-4">
          <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">
            Government IDs
          </h3>

          <div className="grid gap-6 md:grid-cols-2">
            {/* EMIS */}

            <FormField
              control={form.control}
              name="emisNumber"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>EMIS Number</FormLabel>

                  <FormControl>
                    <Input
                      placeholder="Enter EMIS Number"
                      {...field}
                      value={field.value ?? ""}
                    />
                  </FormControl>

                  <FormDescription>
                    Education Management Information
                    System ID (Optional).
                  </FormDescription>

                  <FormMessage />
                </FormItem>
              )}
            />

            {/* APAAR */}

            <FormField
              control={form.control}
              name="apaarId"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>APAAR ID</FormLabel>

                  <FormControl>
                    <Input
                      placeholder="Enter APAAR ID"
                      {...field}
                      value={field.value ?? ""}
                    />
                  </FormControl>

                  <FormDescription>
                    Automated Permanent Academic Account
                    Registry ID (Optional).
                  </FormDescription>

                  <FormMessage />
                </FormItem>
              )}
            />

            {/* PEN */}

            <FormField
              control={form.control}
              name="penNumber"
              render={({ field }) => (
                <FormItem className="md:col-span-2">
                  <FormLabel>PEN Number</FormLabel>

                  <FormControl>
                    <Input
                      placeholder="Enter Permanent Education Number"
                      {...field}
                      value={field.value ?? ""}
                    />
                  </FormControl>

                  <FormDescription>
                    Permanent Education Number issued by
                    the Government (Optional).
                  </FormDescription>

                  <FormMessage />
                </FormItem>
              )}
            />
          </div>
        </div>
      </CardContent>
    </Card>
  );
}